#!/usr/bin/env ruby
src = `pbpaste`

escaped = src.clone
{
  '&' => '&amp;',
  '<' => '&lt;',
  '>' => '&gt;',
  "'" => "'\\''"
}.each do |k,v|
  escaped.gsub!(k){ v }
end

system "echo '#{escaped}' | pbcopy"
