#!/usr/bin/env ruby
require 'tempfile'

clip = `pbpaste`

[{
   '&' => '&amp;'
 },
 {
   '<' => '&lt;',
   '>' => '&gt;' ,
   '"' => '&quot;'
 }
].each do |h|
  h.each do |k,v|
    clip.gsub!(k,v)
  end
end

f = Tempfile.new('clip2htmlescape')
f.write clip
f.close

system "cat #{f.path} | pbcopy"
